<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * `staff_id` is the non-student counterpart to `student_id` — a
     * system-generated ID number for faculty, security officers, and
     * admins, created by the Admin "Create Account" form. Kept as its
     * own nullable/unique column (rather than reusing `student_id`)
     * because:
     *   - the two follow different formats (student_id is chosen by the
     *     student at registration, e.g. 2021-2-04062; staff_id is
     *     generated by the system, e.g. SEC-2026-0001)
     *   - a user should never hold both at once, but keeping them
     *     separate makes that obvious in the schema and avoids format
     *     collisions in validation/uniqueness checks.
     */
    public function up(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->string('staff_id')->nullable()->unique()->after('student_id');
        });
    }

    public function down(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn('staff_id');
        });
    }
};
